### ISSUE TITLE
초기 세팅 추가

### ISSUE THREAD

**Issue by SWLee2973** [FRONTENDSCHOOL8/dosirak#3]
## 💡 Feature Issue

- 초기 세팅

## 📝  Details
- 초기 세팅 추가 설정

## 🌿  To-do

- [x] Tanstack query 라이브러리 추가
- [x] pocketbase 라이브러리 추가
- [x] useForm 라이브러리 추가
- [x] swiper 라이브러리 추가
- [x] 라우터 세팅 추가
