### ISSUE TITLE
모임 기능 잔여 작업

### ISSUE THREAD

**Issue by SWLee2973** [FRONTENDSCHOOL8/dosirak#70]
## 💡 Feature Issue

- 모임 기능 잔여 작업 진행

## 📝  Details
- 모임 생성하기
- 모임 탈퇴하기
- 모임 글쓰기

## 🌿  To-do

- [x] 모임 생성 페이지 마크업
- [x] 모임 생성 기능 구현
- [x] 모임 탈퇴하기 기능 구현
- [x] 모임 글쓰기 기능 구현
