### ISSUE TITLE
모임 화면 컴포넌트 구현

### ISSUE THREAD

**Issue by lanuioe** [FRONTENDSCHOOL8/dosirak#9]
## 💡 Feature Issue

모임 화면 컴포넌트 마크업

## 📝  Details
모임 화면 인기 컴포넌트 마크업 작성
모임 화면 인기 컴포넌트 기능 구현

## 🌿  To-do

- [X] 모임 인기 컴포넌트 마크업
- [X] 모임 리스트 컴포넌트 마크업
- [X] 태그 컴포넌트 구현
- [X] 토글 컴포넌트 구현
